/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.11.5
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client.api';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client.api';
    


// Services

export interface SuperFooDef {
    small_foo: (callParams: CallParams$$<null>) => string | Promise<string>;
}
export function registerSuperFoo(service: SuperFooDef): void;
export function registerSuperFoo(serviceId: string, service: SuperFooDef): void;
export function registerSuperFoo(peer: IFluenceClient$$, service: SuperFooDef): void;
export function registerSuperFoo(peer: IFluenceClient$$, serviceId: string, service: SuperFooDef): void;
       

export function registerSuperFoo(...args: any) {
    registerService$$(
        args,
        {
    "defaultServiceId" : "super_foo",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "small_foo" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions


/* eslint-enable */