/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.11.5
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client.api';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client.api';
    


// Services

export interface SubServiceDef {
    sub: (s: string, callParams: CallParams$$<'s'>) => { one: string; two: number; } | Promise<{ one: string; two: number; }>;
}
export function registerSubService(service: SubServiceDef): void;
export function registerSubService(serviceId: string, service: SubServiceDef): void;
export function registerSubService(peer: IFluenceClient$$, service: SubServiceDef): void;
export function registerSubService(peer: IFluenceClient$$, serviceId: string, service: SubServiceDef): void;
       

export function registerSubService(...args: any) {
    registerService$$(
        args,
        {
    "defaultServiceId" : "sub_service",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "sub" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "s" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "SomeResult",
                            "fields" : {
                                "one" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "two" : {
                                    "tag" : "scalar",
                                    "name" : "u32"
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions
export const subImport_script = `
                    (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (call %init_peer_id% ("sub_service" "sub") ["some thing"] res)
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [res])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                    )
    `
 
export type SubImportResult = { one: string; two: number; }
export function subImport(
    config?: {ttl?: number}
): Promise<SubImportResult>;

export function subImport(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<SubImportResult>;

export function subImport(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "subImport",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "struct",
                    "name" : "SomeResult",
                    "fields" : {
                        "one" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "two" : {
                            "tag" : "scalar",
                            "name" : "u32"
                        }
                    }
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        subImport_script
    )
}

/* eslint-enable */