/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.11.7
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client.api';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client.api';
    


// Services

// Functions
export const iterateAndPrint_script = `
                    (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (call %init_peer_id% ("getDataSrv" "strings") [] strings)
                      )
                      (fold strings s-0
                       (seq
                        (call %init_peer_id% ("println-service-id" "print") [s-0])
                        (next s-0)
                       )
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                    )
    `
 

export function iterateAndPrint(
    strings: string[],
    config?: {ttl?: number}
): Promise<void>;

export function iterateAndPrint(
    peer: IFluenceClient$$,
    strings: string[],
    config?: {ttl?: number}
): Promise<void>;

export function iterateAndPrint(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "iterateAndPrint",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "strings" : {
                    "tag" : "array",
                    "type" : {
                        "tag" : "scalar",
                        "name" : "string"
                    }
                }
            }
        },
        "codomain" : {
            "tag" : "nil"
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        iterateAndPrint_script
    )
}

export const iterateAndPrintParallel_script = `
                    (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (call %init_peer_id% ("getDataSrv" "nodes") [] nodes)
                      )
                      (par
                       (fold nodes s-0
                        (par
                         (seq
                          (call -relay- ("op" "noop") [])
                          (xor
                           (seq
                            (seq
                             (call s-0 ("peer" "identify") [] ads)
                             (call -relay- ("op" "noop") [])
                            )
                            (xor
                             (seq
                              (call %init_peer_id% ("callbackSrv" "c") [ads])
                              (call -relay- ("op" "noop") [])
                             )
                             (seq
                              (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                              (call -relay- ("op" "noop") [])
                             )
                            )
                           )
                           (seq
                            (call -relay- ("op" "noop") [])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                           )
                          )
                         )
                         (next s-0)
                        )
                        (never)
                       )
                       (null)
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
 

export function iterateAndPrintParallel(
    nodes: string[],
    c: (arg0: { air_version: string; external_addresses: string[]; node_version: string; }, callParams: CallParams$$<'arg0'>) => void | Promise<void>,
    config?: {ttl?: number}
): Promise<void>;

export function iterateAndPrintParallel(
    peer: IFluenceClient$$,
    nodes: string[],
    c: (arg0: { air_version: string; external_addresses: string[]; node_version: string; }, callParams: CallParams$$<'arg0'>) => void | Promise<void>,
    config?: {ttl?: number}
): Promise<void>;

export function iterateAndPrintParallel(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "iterateAndPrintParallel",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "nodes" : {
                    "tag" : "array",
                    "type" : {
                        "tag" : "scalar",
                        "name" : "string"
                    }
                },
                "c" : {
                    "tag" : "arrow",
                    "domain" : {
                        "tag" : "unlabeledProduct",
                        "items" : [
                            {
                                "tag" : "struct",
                                "name" : "Info",
                                "fields" : {
                                    "air_version" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    },
                                    "external_addresses" : {
                                        "tag" : "array",
                                        "type" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        }
                                    },
                                    "node_version" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    }
                                }
                            }
                        ]
                    },
                    "codomain" : {
                        "tag" : "nil"
                    }
                }
            }
        },
        "codomain" : {
            "tag" : "nil"
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        iterateAndPrintParallel_script
    )
}

export const to_i_64_script = `
                    (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (call %init_peer_id% ("getDataSrv" "i") [] i)
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [i])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                    )
    `
 

export function to_i_64(
    i: number,
    config?: {ttl?: number}
): Promise<number>;

export function to_i_64(
    peer: IFluenceClient$$,
    i: number,
    config?: {ttl?: number}
): Promise<number>;

export function to_i_64(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "to_i_64",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "i" : {
                    "tag" : "scalar",
                    "name" : "u32"
                }
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "scalar",
                    "name" : "i64"
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        to_i_64_script
    )
}

export const forBug499_script = `
                    (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (new $numbers
                        (seq
                         (seq
                          (seq
                           (new $array-inline
                            (seq
                             (ap "" $array-inline)
                             (canon %init_peer_id% $array-inline  #array-inline-0)
                            )
                           )
                           (fold #array-inline-0 i-0
                            (seq
                             (ap 5 $numbers)
                             (next i-0)
                            )
                           )
                          )
                          (canon %init_peer_id% $numbers  #-numbers-fix-0)
                         )
                         (ap #-numbers-fix-0 -numbers-flat-0)
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [-numbers-flat-0])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                    )
    `
 

export function forBug499(
    config?: {ttl?: number}
): Promise<number[]>;

export function forBug499(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<number[]>;

export function forBug499(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "forBug499",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "array",
                    "type" : {
                        "tag" : "scalar",
                        "name" : "i64"
                    }
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        forBug499_script
    )
}

/* eslint-enable */