/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.11.7
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client.api';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client.api';
    


// Services

// Functions
export const getPeerExternalAddresses_script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                          (call %init_peer_id% ("getDataSrv" "otherNodePeerId") [] otherNodePeerId)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (xor
                         (seq
                          (call otherNodePeerId ("peer" "identify") [] res)
                          (call -relay- ("op" "noop") [])
                         )
                         (seq
                          (call -relay- ("op" "noop") [])
                          (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                         )
                        )
                       )
                       (ap res.$.external_addresses res_flat)
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [res_flat])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
 

export function getPeerExternalAddresses(
    otherNodePeerId: string,
    config?: {ttl?: number}
): Promise<string[]>;

export function getPeerExternalAddresses(
    peer: IFluenceClient$$,
    otherNodePeerId: string,
    config?: {ttl?: number}
): Promise<string[]>;

export function getPeerExternalAddresses(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "getPeerExternalAddresses",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "otherNodePeerId" : {
                    "tag" : "scalar",
                    "name" : "string"
                }
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "array",
                    "type" : {
                        "tag" : "scalar",
                        "name" : "string"
                    }
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        getPeerExternalAddresses_script
    )
}

export const getDistantAddresses_script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                            (call %init_peer_id% ("getDataSrv" "target") [] target)
                           )
                           (call %init_peer_id% ("getDataSrv" "viaNode") [] viaNode)
                          )
                          (call -relay- ("op" "noop") [])
                         )
                         (call viaNode ("op" "noop") [])
                        )
                        (xor
                         (seq
                          (seq
                           (call target ("peer" "identify") [] res)
                           (call viaNode ("op" "noop") [])
                          )
                          (call -relay- ("op" "noop") [])
                         )
                         (seq
                          (seq
                           (call viaNode ("op" "noop") [])
                           (call -relay- ("op" "noop") [])
                          )
                          (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                         )
                        )
                       )
                       (ap res.$.external_addresses res_flat)
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [res_flat])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
 

export function getDistantAddresses(
    target: string,
    viaNode: string,
    config?: {ttl?: number}
): Promise<string[]>;

export function getDistantAddresses(
    peer: IFluenceClient$$,
    target: string,
    viaNode: string,
    config?: {ttl?: number}
): Promise<string[]>;

export function getDistantAddresses(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "getDistantAddresses",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "target" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "viaNode" : {
                    "tag" : "scalar",
                    "name" : "string"
                }
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "array",
                    "type" : {
                        "tag" : "scalar",
                        "name" : "string"
                    }
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        getDistantAddresses_script
    )
}

/* eslint-enable */