/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.11.5
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client.api';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client.api';
    


// Services

export interface UnexistedDef {
    getStr: (callParams: CallParams$$<null>) => string | Promise<string>;
}
export function registerUnexisted(service: UnexistedDef): void;
export function registerUnexisted(serviceId: string, service: UnexistedDef): void;
export function registerUnexisted(peer: IFluenceClient$$, service: UnexistedDef): void;
export function registerUnexisted(peer: IFluenceClient$$, serviceId: string, service: UnexistedDef): void;
       

export function registerUnexisted(...args: any) {
    registerService$$(
        args,
        {
    "defaultServiceId" : "unex",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "getStr" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      


export interface OpEDef {
    identity: (s: string, callParams: CallParams$$<'s'>) => string | Promise<string>;
}
export function registerOpE(service: OpEDef): void;
export function registerOpE(serviceId: string, service: OpEDef): void;
export function registerOpE(peer: IFluenceClient$$, service: OpEDef): void;
export function registerOpE(peer: IFluenceClient$$, serviceId: string, service: OpEDef): void;
       

export function registerOpE(...args: any) {
    registerService$$(
        args,
        {
    "defaultServiceId" : "op",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "identity" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "s" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions
export const tryOtherwiseTest_script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                        (call %init_peer_id% ("getDataSrv" "node_id") [] node_id)
                       )
                       (new $f
                        (seq
                         (seq
                          (call -relay- ("op" "noop") [])
                          (xor
                           (xor
                            (seq
                             (call node_id ("unex" "getStr") [] $f)
                             (call -relay- ("op" "noop") [])
                            )
                            (seq
                             (call node_id ("op" "identity") ["error"] $f)
                             (call -relay- ("op" "noop") [])
                            )
                           )
                           (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                          )
                         )
                         (new $f_test
                          (seq
                           (seq
                            (seq
                             (call %init_peer_id% ("math" "add") [0 1] f_incr)
                             (fold $f f_fold_var
                              (seq
                               (seq
                                (ap f_fold_var $f_test)
                                (canon %init_peer_id% $f_test  #f_iter_canon)
                               )
                               (xor
                                (match #f_iter_canon.length f_incr
                                 (null)
                                )
                                (next f_fold_var)
                               )
                              )
                              (never)
                             )
                            )
                            (canon %init_peer_id% $f_test  #f_result_canon)
                           )
                           (ap #f_result_canon f_gate)
                          )
                         )
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [f_gate.$.[0]])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
 

export function tryOtherwiseTest(
    node_id: string,
    config?: {ttl?: number}
): Promise<string>;

export function tryOtherwiseTest(
    peer: IFluenceClient$$,
    node_id: string,
    config?: {ttl?: number}
): Promise<string>;

export function tryOtherwiseTest(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "tryOtherwiseTest",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "node_id" : {
                    "tag" : "scalar",
                    "name" : "string"
                }
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "scalar",
                    "name" : "string"
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        tryOtherwiseTest_script
    )
}

/* eslint-enable */