addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "2.2.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.16.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.11.0")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"      % "1.10.0")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"               % "5.10.0")
