addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "2.1.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.13.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.1")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.11.0")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"      % "1.9.16")
