package aqua.backend.ts

import aqua.model.AquaContext
import aqua.model.transform.BodyConfig
import cats.data.Chain

case class TypeScriptFile(context: AquaContext) {

  def funcs: Chain[TypeScriptFunc] =
    Chain.fromSeq(context.funcs.values.toSeq).map(TypeScriptFunc(_))

  def services: Chain[TypeScriptService] =
    Chain.fromSeq(context.services.values.toSeq).map(TypeScriptService(_))

  val twoSlashn = System.lineSeparator() + System.lineSeparator()

  def generateTS(conf: BodyConfig = BodyConfig()): String =
    TypeScriptFile.Header + twoSlashn +
      services.map(_.generateTypescript(conf)).toList.mkString(twoSlashn) +
      funcs.map(_.generateTypescript(conf)).toList.mkString(twoSlashn)
}

object TypeScriptFile {

  val Header: String =
    s"""/**
       | *
       | * This file is auto-generated. Do not edit manually: changes may be erased.
       | * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/. 
       | * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
       | * Aqua version: ${Option(getClass.getPackage.getImplementationVersion)
      .filter(_.nonEmpty)
      .getOrElse("Unknown")}
       | *
       | */
       |import { FluenceClient, PeerIdB58 } from '@fluencelabs/fluence';
       |import { RequestFlowBuilder } from '@fluencelabs/fluence/dist/api.unstable';
       |import { RequestFlow } from '@fluencelabs/fluence/dist/internal/RequestFlow';
       |""".stripMargin

}
