package aqua.backend

object Header {

  def header(isJs: Boolean): String =
    s"""/**
       | *
       | * This file is auto-generated. Do not edit manually: changes may be erased.
       | * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
       | * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
       | * Aqua version: ${Version.version}
       | *
       | */
       |import { Fluence, FluencePeer } from '@fluencelabs/fluence';
       |import {
       |    extractFunctionArgs,
       |    CallParams,
       |    ResultCodes,
       |    registerParticleSpecificHandler,
       |    handleTimeout,
       |    extractServiceArgs,
       |    registerCommonHandler,
       |    callFunction,
       |    regService,
       |} from '@fluencelabs/fluence/dist/internal/compilerSupport/v2${if (isJs) ".js" else ""}';
       |""".stripMargin
}
