package aqua.backend.js

import aqua.backend.Version

object JavaScriptFile {

  val Header: String =
    s"""/**
       | *
       | * This file is auto-generated. Do not edit manually: changes may be erased.
       | * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/. 
       | * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
       | * Aqua version: ${Version.version}
       | *
       | */
       |import { RequestFlowBuilder } from '@fluencelabs/fluence/dist/api.unstable.js';
       |""".stripMargin

}
