package aqua.backend.air

import aqua.backend.{Backend, Generated, Version}
import aqua.res.AquaRes
import cats.data.ValidatedNec
import cats.syntax.show.*
import cats.syntax.traverse.*

object AirBackend extends Backend {

  val ext = ".air"

  override def generate(
    aqua: AquaRes,
    airChecker: String => ValidatedNec[String, Unit]
  ): ValidatedNec[String, Seq[Generated]] = {

    val docs = s"""; This file is auto-generated. Do not edit manually: changes may be erased.
                  |; Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
                  |; If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
                  |; Aqua version: ${Version.version}
                  |
                  |""".stripMargin

    aqua.funcs.toList.map { fr =>
      val air = FuncAirGen(fr).generate.show
      airChecker(air).map { _ =>
        val airStr = docs + air
        Generated("." + fr.funcName + ext, airStr)
      }
    }.sequence
  }
}
