name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  aqua:
    name: "aqua"
    if: >
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'e2e')
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  fcli-snapshot:
    name: "fcli"
    needs: aqua
    uses: fluencelabs/flox/.github/workflows/snapshot.yml@main
    with:
      aqua-snapshots: "${{ needs.aqua.outputs.aqua-snapshots }}"

  fcli:
    needs: aqua
    uses: fluencelabs/fluence-cli/.github/workflows/tests.yml@use-js-client-0.5.0
    with:
      aqua-snapshots: "${{ needs.aqua.outputs.aqua-snapshots }}"
      ref: use-js-client-0.5.0

  registry:
    needs:
      - fcli-snapshot
    uses: fluencelabs/registry/.github/workflows/tests.yml@main
    with:
      fcli-version: "${{ needs.fcli-snapshot.outputs.version }}"
