name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  aqua:
    if: >
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'e2e')
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  aqua-playground:
    needs: aqua
    uses: fluencelabs/aqua-playground/.github/workflows/tests.yml@master
    with:
      aqua-version: "${{ needs.aqua.outputs.aqua-version }}"

  registry:
    needs: aqua
    uses: fluencelabs/registry/.github/workflows/tests.yml@main
    with:
      aqua-version: "${{ needs.aqua.outputs.aqua-version }}"

  fluence-cli:
    needs: aqua
    uses: fluencelabs/fluence-cli/.github/workflows/tests.yml@main
    with:
      aqua-version: "${{ needs.aqua.outputs.aqua-version }}"

  aqua-native:
    name: "aqua"
    strategy:
      matrix:
        runner:
          - runs-on: ubuntu-latest
            arch: amd64
            os: linux
            static: true
    needs:
      - aqua
    uses: ./.github/workflows/binary.yml
    with:
      runs-on: ${{ matrix.runner.runs-on }}
      arch: ${{ matrix.runner.arch }}
      os: ${{ matrix.runner.os }}
      static: ${{ matrix.runner.static }}
