name: "e2e"

on:
  pull_request:
    paths-ignode:
      - "**.md"
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    name: "Run sbt tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aqua

      - name: Cache Scala
        uses: coursier/cache-action@v6

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Run tests
        run: sbt test

  aqua:
    name: "aqua"
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  aqua-playground:
    needs: aqua
    uses: fluencelabs/aqua-playground/.github/workflows/tests.yml@master
    with:
      aqua-version: "${{ needs.aqua.outputs.aqua-version }}"

  registry:
    needs: aqua
    uses: fluencelabs/registry/.github/workflows/tests.yml@main
    with:
      aqua-version: "${{ needs.aqua.outputs.aqua-version }}"

  fluence-cli:
    needs: aqua
    uses: fluencelabs/fluence-cli/.github/workflows/tests.yml@main
    with:
      aqua-version: "${{ needs.aqua.outputs.aqua-version }}"
