name: "test"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/run-tests.yml"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/run-tests.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  sbt-tests:
    name: "aqua"
    uses: ./.github/workflows/sbt-tests.yml
    with:
      ref: ${{ github.ref }}
