name: Publish snapshots

on:
  workflow_call:
    inputs:
      sbt-command:
        description: "sbt build command"
        type: string
      working-directory:
        description: "working directory of npm package"
        type: string
      ref:
        description: "git ref to checkout to"
        type: string
        default: "main"
    outputs:
      version:
        description: "package version"
        value: ${{ jobs.publish.outputs.version }}

env:
  FORCE_COLOR: true

jobs:
  publish:
    name: "${{ inputs.sbt-command }}"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    outputs:
      version: "${{ steps.snapshot.outputs.version }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aqua
          ref: ${{ inputs.ref }}

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Cache Scala
        uses: coursier/cache-action@v6

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: JS build
        env:
          SNAPSHOT: ${{ steps.version.outputs.id }}
        run: sbt ${{ inputs.sbt-command }}

      - name: Import secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"
          cache-dependency-path: "*/*-npm/package-lock.json"
          cache: "npm"

      - run: npm i
        working-directory: ${{ inputs.working-directory }}

      - run: npm run build
        working-directory: ${{ inputs.working-directory }}

      - name: Publish snapshot
        id: snapshot
        uses: fluencelabs/github-actions/npm-publish-snapshot@main
        with:
          working-directory: ${{ inputs.working-directory }}
          id: ${{ steps.version.outputs.id }}
