name: Publish snapshots

on:
  workflow_call:
    inputs:
      ref:
        description: "git ref to checkout to"
        type: string
        default: "main"
    outputs:
      aqua-snapshots:
        description: "aqua snapshots"
        value: ${{ jobs.publish.outputs.snapshots }}

env:
  FORCE_COLOR: true
  CI: true

jobs:
  publish:
    name: "Publish snapshots"
    runs-on: builder
    timeout-minutes: 60

    permissions:
      contents: read
      id-token: write

    outputs:
      snapshots: "${{ steps.snapshot.outputs.snapshots }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: fluencelabs/aqua
          ref: ${{ inputs.ref }}

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Cache Scala
        uses: coursier/cache-action@v6

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: scala-js build
        env:
          SNAPSHOT: ${{ steps.version.outputs.id }}
        run: sbt ";language-server-apiJS/fastBundleJS;aqua-apiJS/fastBundleJS"

      - name: Import secrets
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.fluence.dev"
          cache: "pnpm"

      - run: pnpm --filter='!integration-tests' -r i

      - name: Set package version
        run: node ci.cjs bump-version ${{ steps.version.outputs.id }}

      - run: pnpm --filter='!integration-tests' -r build

      - name: Publish snapshot
        id: snapshot
        uses: fluencelabs/github-actions/pnpm-publish-snapshot@main
        with:
          id: ${{ steps.version.outputs.id }}
          set-version: false
