name: Publish snapshots

on:
  workflow_call:
    inputs:
      sbt-command:
        description: "sbt build command"
        type: string
        default: "language-server-apiJS/fastOptJS"
      ref:
        description: "git ref to checkout to"
        type: string
        default: "main"

env:
  FORCE_COLOR: true

jobs:
  compile:
    name: "Compile"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aqua
          ref: ${{ inputs.ref }}

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Cache Scala
        uses: coursier/cache-action@v6

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: JS build
        env:
          SNAPSHOT: ${{ steps.version.outputs.id }}
        run: sbt ${{ inputs.sbt-command }}

      - run: ls -alh language-server/language-server-npm/
