name: Publish snapshots

on:
  workflow_call:
    inputs:
      fluence-js-version:
        description: "@fluencejs/fluence version"
        type: string
        default: "null"
      ref:
        description: "git ref to checkout to"
        type: string
        default: "main"
    outputs:
      aqua-version:
        description: "@fluencelabs/aqua version"
        value: ${{ jobs.aqua.outputs.version }}
      aqua-lsp-api-version:
        description: "@fluencelabs/aqua-language-server-api version"
        value: ${{ jobs.aqua-lsp-api.outputs.version }}
      aqua-api-version:
        description: "@fluencelabs/aqua-api version"
        value: ${{ jobs.aqua-api.outputs.version }}

env:
  FORCE_COLOR: true

jobs:
  compile:
    name: "Compile"
    runs-on: builder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aqua
          ref: ${{ inputs.ref }}

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Cache Scala
        uses: coursier/cache-action@v6

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: JS build
        env:
          BUILD_NUMBER: ${{ steps.version.outputs.id }}
        run: sbt cliJS/fastOptJS

      - name: JS LSP API build
        env:
          BUILD_NUMBER: ${{ steps.version.outputs.id }}
        run: sbt language-server-api/fastOptJS

      - name: JS Aqua API build
        env:
          BUILD_NUMBER: ${{ steps.version.outputs.id }}
        run: sbt aqua-api/fastOptJS

      - name: Upload aqua-js artifact
        uses: actions/upload-artifact@v3
        with:
          name: aqua-js
          path: cli/cli/.js/target/scala-*/cli-fastopt.js

      - name: Upload aqua-js-lsp artifact
        uses: actions/upload-artifact@v3
        with:
          name: aqua-js-lsp
          path: language-server/language-server-api/target/scala-*/language-server-api-fastopt.js

      - name: Upload aqua-js-api artifact
        uses: actions/upload-artifact@v3
        with:
          name: aqua-js-api
          path: api/aqua-api/target/scala-*/aqua-api-fastopt.js

  aqua:
    name: "Publish @fluencelabs/aqua"
    runs-on: ubuntu-latest

    needs: compile

    outputs:
      version: "${{ steps.snapshot.outputs.version }}"

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aqua
          ref: ${{ inputs.ref }}

      - name: Download aqua-js artifact
        uses: actions/download-artifact@v3
        with:
          name: aqua-js

      - run: mv scala-*/cli-fastopt.js cli/cli-npm/aqua.js

      - name: Import secrets
        uses: hashicorp/vault-action@v2.4.3
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"
          cache-dependency-path: "cli/cli-npm/package-lock.json"
          cache: "npm"

      - run: npm i
        working-directory: cli/cli-npm

      - name: Set fluence-js version from branch
        if: inputs.fluence-js-version != 'null'
        working-directory: cli/cli-npm
        run: npm i --save -E @fluencelabs/fluence@${{ inputs.fluence-js-version }}

      - run: npm run build
        working-directory: cli/cli-npm

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Publish snapshot
        id: snapshot
        uses: fluencelabs/github-actions/npm-publish-snapshot@main
        with:
          working-directory: cli/cli-npm
          id: ${{ steps.version.outputs.id }}

  aqua-lsp:
    name: "Publish @fluencelabs/aqua-language-server-api"
    runs-on: ubuntu-latest

    needs: compile

    outputs:
      version: "${{ steps.snapshot.outputs.version }}"

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aqua
          ref: ${{ inputs.ref }}

      - name: Download aqua-js-lsp artifact
        uses: actions/download-artifact@v3
        with:
          name: aqua-js-lsp

      - run: mv scala-*/language-server-api-fastopt.js language-server/language-server-npm/aqua-lsp-api.js

      - name: Import secrets
        uses: hashicorp/vault-action@v2.4.3
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"
          cache-dependency-path: "language-server/language-server-npm/package-lock.json"
          cache: "npm"

      - run: npm i
        working-directory: language-server/language-server-npm

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Publish snapshot
        id: snapshot
        uses: fluencelabs/github-actions/npm-publish-snapshot@main
        with:
          working-directory: language-server/language-server-npm
          id: ${{ steps.version.outputs.id }}

  aqua-api:
    name: "Publish @fluencelabs/aqua-api"
    runs-on: ubuntu-latest

    needs: compile

    outputs:
      version: "${{ steps.snapshot.outputs.version }}"

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aqua
          ref: ${{ inputs.ref }}

      - name: Download aqua-js artifact
        uses: actions/download-artifact@v3
        with:
          name: aqua-js-api

      - run: mv scala-*/aqua-api-fastopt.js api/aqua-api-npm/aqua-api.js

      - name: Import secrets
        uses: hashicorp/vault-action@v2.4.3
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"
          cache-dependency-path: "api/aqua-api-npm/package-lock.json"
          cache: "npm"

      - run: npm i
        working-directory: api/aqua-api-npm

      - name: Set fluence-js version from branch
        if: inputs.fluence-js-version != 'null'
        working-directory: cli/cli-npm
        run: npm i --save-dev -E @fluencelabs/fluence@${{ inputs.fluence-js-version }}

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Publish snapshot
        id: snapshot
        uses: fluencelabs/github-actions/npm-publish-snapshot@main
        with:
          working-directory: api/aqua-api-npm
          id: ${{ steps.version.outputs.id }}
