name: Publish snapshot

on:
  workflow_call:
    inputs:
      fluence-js-version:
        description: "@fluencejs/fluence version"
        type: string
    outputs:
      aqua-version:
        description: "@fluencelabs/aqua version"
        value: ${{ jobs.publish-snapshot.outputs.aqua-version }}

env:
  FORCE_COLOR: true

jobs:
  compile:
    name: "Compile"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aqua

      - name: Generate version
        id: version
        run: |
          SHA=${{ github.event.pull_request.head.sha }}
          echo "sha=${SHA::7}" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_HEAD_REF//[^a-zA-Z0-9-]/-}" >> $GITHUB_OUTPUT

      - name: Cache Scala
        uses: coursier/cache-action@v6

      - name: Setup Scala
        uses: coursier/setup-action@v1

      - name: Compile aqua
        env:
          BUILD_NUMBER: ${{ steps.version.outputs.branch }}-${{ steps.version.outputs.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
        run: sbt "cliJS/fastOptJS"

      - name: Upload compiled aqua
        uses: actions/upload-artifact@v3
        with:
          name: aqua
          path: cli/.js/target/scala-*/cli-fastopt.js

  publish-snapshot:
    name: "Publish snapshot"
    runs-on: ubuntu-latest

    needs: compile

    outputs:
      aqua-version: "${{ steps.snapshot.outputs.version }}"

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout aqua
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aqua

      - name: Download compiled aqua
        uses: actions/download-artifact@v3
        with:
          name: aqua

      - run: mv scala-*/cli-fastopt.js npm/aqua.js

      - name: Import secrets
        uses: hashicorp/vault-action@v2.4.3
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"
          cache-dependency-path: "npm/package-lock.json"
          cache: "npm"

      - run: npm i
        working-directory: npm

      - name: Set fluence-js version from branch
        if: inputs.fluence-js-version != ''
        working-directory: npm
        run: npm i --save -E @fluencelabs/fluence@${{ inputs.fluence-js-version }}

      - run: npm run build
        working-directory: npm

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@FLU-120-add-npm-publish-snapshot

      - name: Publish snapshot
        id: snapshot
        uses: fluencelabs/github-actions/npm-publish-snapshot@FLU-120-add-npm-publish-snapshot
        with:
          working-directory: npm
          id: ${{ steps.version.outputs.id }}
